{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: app-secret-store
    kind: SecretStore
  target:
    name: app-external-secrets
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecrets.secrets }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .remoteRef.key }}
      property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}