apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.rollout.name }}
  namespace: {{ .Values.rollout.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: expo
  template:
    metadata:
      labels:
        app: expo
    spec:
      terminationGracePeriodSeconds: {{ .Values.rollout.terminationGracePeriodSeconds}}
      containers:
        - name: expo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
  strategy:
    blueGreen:
      activeService: product-active
      previewService: product-preview
      autoPromotionEnabled: {{ .Values.rollout.strategy.autoPromotionEnabled }}
      autoPromotionSeconds: {{ .Values.rollout.strategy.autoPromotionSeconds }}
      scaleDownDelaySeconds: {{ .Values.rollout.strategy.scaleDownDelaySeconds }}
