{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.rollout.name }}
  namespace: {{ .Values.rollout.namespace }}
spec:
  replicas: {{ .Values.rollout.replicaCount }}
  selector:
    matchLabels:
      app: expo
  template:
    metadata:
      labels:
        app: expo
    spec:
      terminationGracePeriodSeconds: {{ .Values.rollout.terminationGracePeriodSeconds}}
      containers:
        - name: expo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.rollout.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.rollout.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.rollout.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.rollout.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.rollout.readinessProbe.failureThreshold }}
          env:
          {{- $secretName := .Values.externalSecrets.name }}
          {{- range .Values.externalSecrets.secrets }}
            - name: {{ .secretKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .secretKey }}
          {{- end }}
  strategy:
    blueGreen:
      activeService: app-active
      previewService: app-preview
      autoPromotionEnabled: {{ .Values.rollout.strategy.blueGreen.autoPromotionEnabled }}
      autoPromotionSeconds: {{ .Values.rollout.strategy.blueGreen.autoPromotionSeconds }}
      scaleDownDelaySeconds: {{ .Values.rollout.strategy.blueGreen.scaleDownDelaySeconds }}
{{- end }}