{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: app-active
  namespace: {{ .Values.rollout.namespace }}
spec:
  selector:
    app: expo
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
{{- end }}